### ISSUE TITLE
Copyright notice update

### ISSUE THREAD

**Issue by barotto** [mikke89/RmlUiDoc#1]
I think the copyright notice should be updated, adding to the existing notice
```
Copyright (c) 2019 $YOUR NAME(S), and contributors
```
or
```
Copyright (c) 2019 The RmlUi Team, and contributors
```

Of course this should be done for the codebase as well.

Thoughts?

**Comment by mikke89** [comment]
I agree. Not sure which name(s) to put, but I like the RmlUi Team :)

**Comment by barotto** [comment]
Ok, RmlUi Team it is :)

Go RmlUi Team!

**Comment by mikke89** [comment]
Yes, we are officially a team now! :)
