### ISSUE TITLE
Mouse Cursors

### ISSUE THREAD

**Issue by barotto** [mikke89/RmlUiDoc#2]
As I understand, mikke89/RmlUi@957f7239d61209ff35799ead931fe98f9853d836 introduces some substantial differences with libRocket in the way mouse cursors are managed.

The current doc at https://mikke89.github.io/RmlUiDoc/pages/cpp_manual/contexts.html#cursors seems now incorrect.

Can you elaborate on how mouse cursors now work?

**Comment by mikke89** [comment]
You're right, I will the documentation for this. Thanks for pointing it out to me. The short version is that it's moved to the system interface. I'll try to make an example for e.g. the invaders sample as well.

Oh and I keep seeing all these commits from you, and just wanted to let you know that it's really appreciated. Thanks! :)

**Comment by barotto** [comment]
> Oh and I keep seeing all these commits from you, and just wanted to let you know that it's really appreciated. Thanks! :)

Well, I think a library is as good as its documentation.

Docs are an integral part still nobody wants to work on them... I might as well finish what I started, merge this work in my libRocketDoc repo (minus RmlUi specific parts), and give any other libRocket fork a nice foundation to build upon ;)

**Comment by mikke89** [comment]
That's a great attitude, and will certainly help the whole librocket community. :)

I've added adescription of the mouse cursors in dce1fb8cd2d9fbdeef5a9936b4354c7a6dac93d9. Let me know if anything is unclear.
