### ISSUE TITLE
Latest commit build problem

### ISSUE THREAD

**Issue by barotto** [mikke89/RmlUiDoc#3]
748f97e9eeeb272e774cd8acb87e6e63abebe968 won't build for some unknown reason. I received an email with just "try again later".
Can you check under the repo's "Settings"/"GitHub Pages" section, please?

**Comment by mikke89** [comment]
That's strange, it doesn't give us any more information:

>  Your site is having problems building: Unable to build page. Please try again later.

No option to try again from there, maybe just try pushing another commit?

**Comment by barotto** [comment]
Ok I pushed a commit and the site was successfully built.
Maybe It was a gh-pages outage.

**Comment by mikke89** [comment]
Good thing it's working now, just software being software sometimes :P
