### ISSUE TITLE
Document unloading

### ISSUE THREAD

**Issue by barotto** [mikke89/RmlUiDoc#7]
I think there's a couple of errors/inconsistencies about document unloading.

* in `faq.md:52` `Context::CloseDocument()` is used but the function doesn't exists; should be `my_document->Close()`.
* in `integrating.md:111` is suggested to use `Context::UnloadDocument()`; while not incorrect, I think `ElementDocument::Close()` would be more appropriate.

What do you think?

**Comment by mikke89** [comment]
Thanks, good observation! I agree that `my_document->Close()` should be the idiomatic approach, and should be used in the documentation.

Could you make a PR? Thanks!
